name: Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3  # Upgrade to v3
      - name: Source hosts.sh
        run: |
          chmod +x ./hosts.sh
      - name: Run tests
        run: |
          chmod +x tests/test_hosts.sh
          bash tests/test_hosts.sh